### ISSUE TITLE
Mirel NZ5 Taurus 

### ISSUE THREAD

**Issue by Mates854** [JachyHm/RailWorksLUAscriptExamples#3]
[Při zásahu Mirelu chybou NZ5 a dalších nejde tlačítkem Entr potvrdit Mirel pro znovu nastavení a pokračování v jízdě. Po chvíli mačkání tlačítka Entr na displeji problikávají zkratky PRE a NZ5 ale ani jedno z toho nejde potvrdit. Je třeba hru uložit a znovu načíst aby šlo pokračovat v jízdě. @JachyHm

**Comment by JachyHm** [comment]
Chybí potřebné informace - kdy přesně k zásahu dojde? Bylo v době zásahu loko zajištěná proti ujetí přímočinnou brzdou? Bylo při potvrzování loko zajištěná přímočinnou brzdou?
Mohl by jsi nejlépe natočit video?
